/**
 * Payment screen.
 * Shows tariff plans, initiates Telegram Stars or Robokassa payment.
 */

const PLANS = [
  { key: "plan_30",  label: "30 дней",  stars: 150, rub: 199 },
  { key: "plan_90",  label: "90 дней",  stars: 400, rub: 499 },
  { key: "plan_180", label: "180 дней", stars: 700, rub: 899 },
];

export default function Payment({ onBack }) {
  const haptic = (type = "impact") => {
    window.Telegram?.WebApp?.HapticFeedback?.impactOccurred?.(type);
  };

  const handleStars = (plan) => {
    haptic("medium");
    // Invoke Stars payment via bot: send a message that triggers the invoice
    window.Telegram?.WebApp?.sendData(JSON.stringify({ action: "buy_stars", plan: plan.key }));
  };

  const handleRobokassa = (plan) => {
    haptic("medium");
    // Open Robokassa payment URL (generated by bot backend)
    const url = `${import.meta.env.VITE_API_URL}/api/payment/robokassa?plan=${plan.key}` +
      `&tg_id=${window.Telegram?.WebApp?.initDataUnsafe?.user?.id}`;
    window.Telegram?.WebApp?.openLink(url);
  };

  return (
    <div className="flex flex-col gap-4 p-4 max-w-md mx-auto">
      {/* Back button */}
      <button
        className="text-tg-link text-sm self-start"
        onClick={onBack}
      >
        ← Назад
      </button>

      <h2 className="text-xl font-bold">Выберите тариф</h2>

      {PLANS.map((plan) => (
        <div key={plan.key} className="glass-card p-5 flex flex-col gap-3">
          <div className="flex justify-between items-center">
            <span className="font-semibold text-lg">{plan.label}</span>
            <span className="text-tg-hint text-sm">⭐{plan.stars} / {plan.rub}₽</span>
          </div>
          <div className="flex gap-2">
            <button
              className="flex-1 py-2 rounded-xl bg-tg-button text-tg-buttonText font-medium text-sm"
              onClick={() => handleStars(plan)}
            >
              ⭐ Оплатить Stars
            </button>
            <button
              className="flex-1 py-2 rounded-xl border border-tg-button text-tg-button font-medium text-sm"
              onClick={() => handleRobokassa(plan)}
            >
              💳 Оплатить ₽
            </button>
          </div>
        </div>
      ))}

      <p className="text-tg-hint text-xs text-center mt-2">
        Оплата через Telegram Stars или банковскую карту (Robokassa).
        Возврат средств — по запросу в течение 14 дней.
      </p>
    </div>
  );
}
